name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: barath2005
          password: ${{ secrets.DOCKER_PASSWD }}
          ecr: false
          logout: true

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag barath2005/project-demo:1.0

      - name: Push the Docker image
        run: docker push barath2005/project-demo:1.0
